version: '3.8'
services:
  
  postgres:
    image: postgres:15.2
    restart: always
    env_file:
      - api/.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
   name: postgres